server {
    listen 80;
    # ОБЯЗАТЕЛЬНО ВПИШИТЕ ВАШ КУПЛЕННЫЙ ДОМЕН НИЖЕ:
    server_name o6oyudno.tech;

    # Специальный путь, куда придет Certbot проверять домен
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Всех остальных пользователей пока перенаправляем на HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}